# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['Main_Modulos_Intro_Pages.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('*.json', '.'),
        ('./json/*.json', './json/'),
        ('./Icons/*.jpg', './Icons/'),
        ('./Icons/leaderboard_icon.png', './Icons/'),
        ('./Icons/completado_icon.png', './Icons/'),
        ('./Icons/*.jpeg', './Icons/'),
        ('./Codigos_LeaderBoard/*.json', './Codigos_LeaderBoard/'),
         ('./active_widgets/game_elements_visibility.json', './active_widgets/'),
        ('./Page_Order/*.json', './Page_Order/'),
        ('./game_features/*.json', './game_features/'),
        ('./Usuarios_respuestas_entrevista/', './Usuarios_respuestas_entrevista/'),
        ('./M1_LESSON_1_Codification/*.json', './M1_LESSON_1_Codification/'),
        ('./M1_LESSON_2_Working_with_Numerical_Data/*.json', './M1_LESSON_2_Working_with_Numerical_Data/'),
        ('./M1_LESSON_3_Working_with_Text_Data/*.json', './M1_LESSON_3_Working_with_Text_Data/'),
        ('./M1_LESSON_4_Mixing_things_up/*.json', './M1_LESSON_4_Mixing_things_up/'),
        ('./M1_LESSON_5_Labeling_Storing_and_Handling_Data_with_Variables/*.json', './M1_LESSON_5_Labeling_Storing_and_Handling_Data_with_Variables/'),       
        ('./M2_LESSON_1_Taking_User_Input/*.json', './M2_LESSON_1_Taking_User_Input/'),
        ('./M2_LESSON_2_Working_with_Input/*.json', './M2_LESSON_2_Working_with_Input/'),
        ('./M2_LESSON_3_In_Place_Operators/*.json', './M2_LESSON_3_In_Place_Operators/'),
        ('./M3_LESSON_1_Booleans_and_Comparisons/*.json', './M3_LESSON_1_Booleans_and_Comparisons/'),
        ('./M3_LESSON_2_If_Statements/*.json', './M3_LESSON_2_If_Statements/'),
        ('./M3_LESSON_3_Else_Statements/*.json', './M3_LESSON_3_Else_Statements/'),
        ('./M3_LESSON_4_Boolean_Logic/*.json', './M3_LESSON_4_Boolean_Logic/'),
        ('./M3_LESSON_5_while_Loops/*.json', './M3_LESSON_5_while_Loops/'),
        ('./M4_LESSON_1_Lists/*.json', './M4_LESSON_1_Lists/'),
        ('./M4_LESSON_2_List_Operations/*.json', './M4_LESSON_2_List_Operations/'),
        ('./M4_LESSON_3_For_Loops/*.json', './M4_LESSON_3_For_Loops/'),
        ('./M4_LESSON_4_Ranges/*.json', './M4_LESSON_4_Ranges/'),
        ('./M4_LESSON_5_List_Slices/*.json', './M4_LESSON_5_List_Slices/'),
        ('./M5_LESSON_1_Functions/*.json', './M5_LESSON_1_Functions/'),
        ('./M5_LESSON_2_List_Functions/*.json', './M5_LESSON_2_List_Functions/'),
        ('./M5_LESSON_3_String_Functions/*.json', './M5_LESSON_3_String_Functions/'),
        ('./M5_LESSON_4_Making_Your_Own_Functions/*.json', './M5_LESSON_4_Making_Your_Own_Functions/'),
        ('./M5_LESSON_5_Function_Arguments/*.json', './M5_LESSON_5_Function_Arguments/'),
        ('./M5_LESSON_6_Returning_From_Functions/*.json', './M5_LESSON_6_Returning_From_Functions/'),
        ('./M5_LESSON_7_Comments_and_Docstrings/*.json', './M5_LESSON_7_Comments_and_Docstrings/')
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PyQt5'],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Main_Modulos_Intro_Pages',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
